### ISSUE TITLE
楼主好，有体验pandora大神那个自动获取acess token的吗？

### ISSUE THREAD

**Issue by iallu** [xueandyue/ChatGPT-3.5-AccessToken-Web#1]
我体验后失败了，同时不知道错误在哪里。
Login begin: [lulu2003@aigcchatgpt.xyz](mailto:lulu2003@aigcchatgpt.xyz), 1/20
Login failed: [lulu2003@aigcchatgpt.xyz](mailto:lulu2003@aigcchatgpt.xyz), HTTPSConnectionPool(host='auth0.openai.com', port=443): Max retries exceeded with url: /authorize?client_id=pdlLIX2Y72MIl2rhLhTE9VV9bN905kBh&audience=https%3A%2F%2Fapi.openai.com%2Fv1&redirect_uri=com.openai.chat%3A%2F%2Fauth0.openai.com%2Fios%2Fcom.openai.chat%2Fcallback&scope=openid%20email%20profile%20offline_access%20model.request%20model.read%20organization.read%20offline&response_type=code&code_challenge=w6n3Ix420Xhhu-Q5-mOOEyuPZmAsJHUbBpO8Ub7xBCY&code_challenge_method=S256&prompt=login (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021E974CC910>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
Login begin: [putilaozu1688@aigcchatgpt.xyz](mailto:putilaozu1688@aigcchatgpt.xyz), 2/20

**Comment by xueandyue** [comment]
没尝试过。你可以试试手动用postman调接口，看是否能排除代码的问题。
