### ISSUE TITLE
这两个是添加openai官方的账号密码吗？

### ISSUE THREAD

**Issue by aa335711** [xueandyue/ChatGPT-3.5-AccessToken-Web#10]
如题

${username}是账号的值，${password}是账号的密码，

**Comment by xueandyue** [comment]
> 如题
> 
> ${username}是账号的值，${password}是账号的密码，

![image](https://github.com/xueandyue/ChatGPT-3.5-AccessToken-Web/assets/16577210/109242a8-76f8-4148-96f0-2d353336efb1)
![image](https://github.com/xueandyue/ChatGPT-3.5-AccessToken-Web/assets/16577210/cd049e54-2b42-419d-8592-a325aed94ddf)

**Comment by aa335711** [comment]
好的，谢谢
