### ISSUE TITLE
不知道有没有可能会出现gpt账号密码泄露的情况

### ISSUE THREAD

**Issue by dislazy** [xueandyue/ChatGPT-3.5-AccessToken-Web#13]
这个直接输入账号和密码之后 会自动获取access token吗  是通过第三方获取的对吧  所以有没有可能会出现密码泄露

**Comment by xueandyue** [comment]
> 这个直接输入账号和密码之后 会自动获取access token吗 是通过第三方获取的对吧 所以有没有可能会出现密码泄露

用到https://ai-20230626.fakeopen.com/auth的服务，是否可能泄露不好说。不过花几块钱就能买一个新号。
