### ISSUE TITLE
请问是不是整pandora项目都挂掉了？8月17号晚上10点左右

### ISSUE THREAD

**Issue by r81892489** [xueandyue/ChatGPT-3.5-AccessToken-Web#15]
更新token还是返回失败。然后逛了下pandora的提问区好像炸锅了，跟openai开启验证有关？
然后网页端莫名其妙多出来一个广告？？？开始欢迎词被魔改成广告？什么操作啊图穷匕见吗

**Comment by xueandyue** [comment]
啥？啥广告？

**Comment by r81892489** [comment]
> 啥？啥广告？

部署完web ui上有个欢迎词，和贴片广告，什么服务器部署加群加微信的…最重要的是现在部署返回消息错误，提示未知错误请联系管理员，被迫直接拉了pandora,用了，还挺喜欢nextweb的界面的

**Comment by r81892489** [comment]
> > > 啥？啥广告？
> > 
> > 
> > 部署完web ui上有个欢迎词，和贴片广告，什么服务器部署加群加微信的…最重要的是现在部署返回消息错误，提示未知错误请联系管理员，被迫直接拉了pandora,用了，还挺喜欢nextweb的界面的
> 
> 早就不需要手动更新token了，请认准检查docker镜像版本和docker命令 docker pull xueandyue/next-web-pandora:latest docker run -e username="你的gpt账号" -e password="你的gpt账号密码" -e CODE="${CODE}" -p 3000:3000 -d xueandyue/next-web-pandora:latest

原来如此，可是我用的是谷歌账户登陆的，安全考虑还是不太放心。有空再拉回来试试吧，还有那个广告真的太…本来挺美观的界面整得乌烟瘴气的…还是用原版算了

**Comment by xueandyue** [comment]
> > > > 啥？啥广告？
> > > 
> > > 
> > > 部署完web ui上有个欢迎词，和贴片广告，什么服务器部署加群加微信的…最重要的是现在部署返回消息错误，提示未知错误请联系管理员，被迫直接拉了pandora,用了，还挺喜欢nextweb的界面的
> > 
> > 
> > 早就不需要手动更新token了，请认准检查docker镜像版本和docker命令 docker pull xueandyue/next-web-pandora:latest docker run -e username="你的gpt账号" -e password="你的gpt账号密码" -e CODE="${CODE}" -p 3000:3000 -d xueandyue/next-web-pandora:latest
> 
> 原来如此，可是我用的是谷歌账户登陆的，安全考虑还是不太放心。有空再拉回来试试吧，还有那个广告真的太…本来挺美观的界面整得乌烟瘴气的…还是用原版算了

出现广告估计你用的不是我维护的docker镜像版本，我只维护这个 xueandyue/next-web-pandora:latest

**Comment by r81892489** [comment]
> 

感谢百忙抽空解答，有空再测试，之前拉的镜像是:v1，报错好像是pandora被攻击造成的。现已解决。

**Comment by xueandyue** [comment]
现在这个项目不支持第三方账号，只支持账号密码的方式，pandora目前的确最适合你的
