### ISSUE TITLE
请教一下,access token更新或获取的脚本路径在哪？

### ISSUE THREAD

**Issue by walkchen9** [xueandyue/ChatGPT-3.5-AccessToken-Web#19]
这个版本应该是不能轮询，且反向代理只有一个，挂了就很被动。
想自动获取或更新token，我用脚本的方式去更新其他线路的gpt。

**Comment by xueandyue** [comment]
不太理解要去轮询什么，本项目会定时更新token，你可以参考下dockerfile文件

**Comment by walkchen9** [comment]
> 不太理解要去轮询什么，本项目会定时更新token，你可以参考下dockerfile文件

已经找到脚本了
用户多的话，轮询可以多个提问并发

**Comment by xueandyue** [comment]
轮询多个accesstoken的方式，本项目不计划支持。一般人没有大量用户的情况，本项目主要是针对个人可以不用魔法，低成本快速搭建一个应用，和周围的人一起使用的场景。

**Comment by walkchen9** [comment]
公司使用还是会存在并发的可能，轮询可以解决，一般也就三四个账号。
另外想请教一下是否有支持Plus使用token的方式项目？

**Comment by xueandyue** [comment]
针对plus,本项目有gpt4分支，之前能用，后面没维护那个分支了。
