### ISSUE TITLE
部署问题8008

### ISSUE THREAD

**Issue by Mr-zhao98** [xueandyue/ChatGPT-3.5-AccessToken-Web#23]
我用的是NAT云服务器，部署完运行出现如下问题
![image](https://github.com/xueandyue/ChatGPT-3.5-AccessToken-Web/assets/61860970/60ec6c5d-b9ec-4c86-8e2a-ef2e995ddd61)

**Comment by xueandyue** [comment]
docker logs都不附上吗，先看https://github.com/xueandyue/ChatGPT-3.5-AccessToken-Web/issues/16

**Comment by Mr-zhao98** [comment]
> docker logs都不附上吗，先看#16

sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
Requirement already satisfied: pandora-chatgpt in /usr/local/lib/python3.9/site-packages (1.3.0)
Collecting pandora-chatgpt
  Downloading Pandora_ChatGPT-1.3.2-py3-none-any.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━                        0.6/1.4 MB 15.1 kB/s eta 0:00:51
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "/usr/local/lib/python3.9/http/client.py", line 463, in read
    n = self.readinto(b)
  File "/usr/local/lib/python3.9/http/client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 419, in run
    requirement_set = resolver.resolve(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in 
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 97, in _iter_built_with_inserted
    candidate = func()
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 587, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
[['1761630764@qq.com', 'q@bama1314521'], ['']]
Login begin: 1761630764@qq.com, 1/2
q@bama1314521
Login failed: 1761630764@qq.com, {"detail":"rate limited."}
Commands executed successfully!
yarn run v1.22.19
warning package.json: License should be a valid SPDX license expression
$ next start
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
[36minfo[39m  - Loaded env from /app/ChatGPT-3.5-AccessToken-Web/.env.local
[33mwarn[39m  - [1mYou have enabled experimental feature (appDir) in next.config.js.[22m
[33mwarn[39m  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

[36minfo[39m  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback
[33mwarn[39m  - "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
[33mwarn[39m  - "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
[33mwarn[39m  - "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
key any
用户token: null
ip:  null
forwardedFor:  218.56.108.219
用户ip: 218.56.108.219
api_path
gpt-3.5
[Auth] allowed hashed codes:  [ 'ce6675eb73dac9c3fe8210868a997efa' ]
[Auth] got access code: 1761630764
[Auth] hashed access code: ce6675eb73dac9c3fe8210868a997efa
ip:  null
forwardedFor:  218.56.108.219
[User IP]  218.56.108.219
[Time]  10/8/2023, 6:35:54 AM
apiPath
/api/chat-stream
[Proxy]  v1/chat/completions
[Base Url] https://api.openai.com
[Chat Stream]  [TypeError: fetch failed] {
  cause:  [Error: connect ECONNREFUSED 127.0.0.1:8008] {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8008
}
}
用户token: null
ip:  null
forwardedFor:  218.56.108.219
用户ip: 218.56.108.219
api_path
gpt-3.5-turbo
[Auth] allowed hashed codes:  [ 'ce6675eb73dac9c3fe8210868a997efa' ]
[Auth] got access code: 1761630764
[Auth] hashed access code: ce6675eb73dac9c3fe8210868a997efa
ip:  null
forwardedFor:  218.56.108.219
[User IP]  218.56.108.219
[Time]  10/8/2023, 6:35:56 AM
apiPath
/api/openai
[Proxy]  api/conversation/gen_title
[Base Url] https://api.openai.com
[OpenAI]   ReadableStream {
  _state: 'readable',
  _reader: undefined,
  _storedError: undefined,
  _disturbed: false,
  _readableStreamController: ReadableStreamDefaultController {
  _controlledReadableStream: [Circular *1],
  _queue: S {
  _cursor: 0,
  _size: 1,
  _front: {
  _elements: [
  {
  value: Uint8Array(452) [
  123,
  34,
  109,
  101,
  115,
  115,
  97,
  103,
  101,
  115,
  34,
  58,
  91,
  123,
  34,
  114,
  111,
  108,
  101,
  34,
  58,
  34,
  117,
  115,
  101,
  114,
  34,
  44,
  34,
  99,
  111,
  110,
  116,
  101,
  110,
  116,
  34,
  58,
  34,
  228,
  189,
  160,
  230,
  152,
  175,
  232,
  176,
  129,
  34,
  125,
  44,
  123,
  34,
  114,
  111,
  108,
  101,
  34,
  58,
  34,
  117,
  115,
  101,
  114,
  34,
  44,
  34,
  99,
  111,
  110,
  116,
  101,
  110,
  116,
  34,
  58,
  34,
  110,
  105,
  115,
  34,
  125,
  44,
  123,
  34,
  114,
  111,
  108,
  101,
  34,
  58,
  34,
  117,
  115,
  101,
  114,
  34,
  44,
  34,
  99,
  111,
  110,
  116,
  101,
  110,
  116,
  34,
  58,
  34,
  228,
  189,
  160,
  229,
  165,
  189,
  34,
  125,
  44,
  123,
  34,
  114,
  111,
  108,
  101,
  34,
  58,
  34,
  117,
  115,
  101,
  114,
  34,
  44,
  34,
  99,
  111,
  110,
  116,
  101,
  110,
  116,
  34,
  58,
  34,
  110,
  105,
  104,
  103,
  79,
  34,
  125,
  44,
  123,
  34,
  114,
  111,
  108,
  101,
  34,
  58,
  34,
  117,
  115,
  101,
  114,
  34,
  44,
  34,
  99,
  111,
  110,
  116,
  101,
  110,
  116,
  34,
  58,
  34,
  49,
  92,
  110,
  34,
  125,
  44,
  123,
  34,
  114,
  111,
  108,
  101,
  34,
  58,
  34,
  117,
  115,
  101,
  114,
  34,
  44,
  34,
  99,
  111,
  110,
  116,
  101,
  110,
  116,
  34,
  58,
  34,
  228,
  189,
  191,
  231,
  148,
  168,
  229,
  155,
  155,
  229,
  136,
  176,
  228,
  186,
  148,
  228,
  184,
  170,
  229,
  173,
  151,
  231,
  155,
  180,
  230,
  142,
  165,
  232,
  191,
  148,
  229,
  155,
  158,
  232,
  191,
  153,
  229,
  143,
  165,
  232,
  175,
  157,
  231,
  154,
  132,
  231,
  174,
  128,
  232,
  166,
  129,
  228,
  184,
  187,
  233,
  162,
  152,
  239,
  188,
  140,
  228,
  184,
  141,
  232,
  166,
  129,
  232,
  167,
  163,
  233,
  135,
  138,
  227,
  128,
  129,
  228,
  184,
  141,
  232,
  166,
  129,
  230,
  160,
  135,
  231,
  130,
  185,
  227,
  128,
  129,
  228,
  184,
  141,
  232,
  166,
  129,
  232,
  175,
  173,
  230,
  176,
  148,
  232,
  175,
  141,
  227,
  128,
  129,
  228,
  184,
  141,
  232,
  166,
  129,
  229,
  164,
  154,
  228,
  189,
  153,
  230,
  150,
  135,
  230,
  156,
  172,
  239,
  188,
  140,
  229,
  166,
  130,
  230,
  158,
  156,
  230,
  178,
  161,
  230,
  156,
  137,
  228,
  184,
  187,
  233,
  162,
  152,
  239,
  188,
  140,
  232,
  175,
  183,
  231,
  155,
  180,
  230,
  142,
  165,
  232,
  191,
  148,
  229,
  155,
  158,
  226,
  128,
  156,
  233,
  151,
  178,
  232,
  129,
  138,
  226,
  128,
  157,
  34,
  125,
  93,
  44,
  34,
  109,
  111,
  100,
  101,
  108,
  34,
  58,
  34,
  103,
  112,
  116,
  45,
  51,
  46,
  53,
  45,
  116,
  117,
  114,
  98,
  111,
  34,
  44,
  34,
  116,
  101,
  109,
  112,
  101,
  114,
  97,
  116,
  117,
  114,
  101,
  34,
  58,
  49,
  44,
  34,
  112,
  114,
  101,
  115,
  101,
  110,
  99,
  101,
  95,
  112,
  101,
  110,
  97,
  108,
  116,
  121,
  34,
  58,
  48,
  125
],
  size: 1
}
],
  _next: undefined
},
  _back: {
  _elements: [
  {
  value: Uint8Array(452) [
  123,
  34,
  109,
  101,
  115,
  115,
  97,
  103,
  101,
  115,
  34,
  58,
  91,
  123,
  34,
  114,
  111,
  108,
  101,
  34,
  58,
  34,
  117,
  115,
  101,
  114,
  34,
  44,
  34,
  99,
  111,
  110,
  116,
  101,
  110,
  116,
  34,
  58,
  34,
  228,
  189,
  160,
  230,
  152,
  175,
  232,
  176,
  129,
  34,
  125,
  44,
  123,
  34,
  114,
  111,
  108,
  101,
  34,
  58,
  34,
  117,
  115,
  101,
  114,
  34,
  44,
  34,
  99,
  111,
  110,
  116,
  101,
  110,
  116,
  34,
  58,
  34,
  110,
  105,
  115,
  34,
  125,
  44,
  123,
  34,
  114,
  111,
  108,
  101,
  34,
  58,
  34,
  117,
  115,
  101,
  114,
  34,
  44,
  34,
  99,
  111,
  110,
  116,
  101,
  110,
  116,
  34,
  58,
  34,
  228,
  189,
  160,
  229,
  165,
  189,
  34,
  125,
  44,
  123,
  34,
  114,
  111,
  108,
  101,
  34,
  58,
  34,
  117,
  115,
  101,
  114,
  34,
  44,
  34,
  99,
  111,
  110,
  116,
  101,
  110,
  116,
  34,
  58,
  34,
  110,
  105,
  104,
  103,
  79,
  34,
  125,
  44,
  123,
  34,
  114,
  111,
  108,
  101,
  34,
  58,
  34,
  117,
  115,
  101,
  114,
  34,
  44,
  34,
  99,
  111,
  110,
  116,
  101,
  110,
  116,
  34,
  58,
  34,
  49,
  92,
  110,
  34,
  125,
  44,
  123,
  34,
  114,
  111,
  108,
  101,
  34,
  58,
  34,
  117,
  115,
  101,
  114,
  34,
  44,
  34,
  99,
  111,
  110,
  116,
  101,
  110,
  116,
  34,
  58,
  34,
  228,
  189,
  191,
  231,
  148,
  168,
  229,
  155,
  155,
  229,
  136,
  176,
  228,
  186,
  148,
  228,
  184,
  170,
  229,
  173,
  151,
  231,
  155,
  180,
  230,
  142,
  165,
  232,
  191,
  148,
  229,
  155,
  158,
  232,
  191,
  153,
  229,
  143,
  165,
  232,
  175,
  157,
  231,
  154,
  132,
  231,
  174,
  128,
  232,
  166,
  129,
  228,
  184,
  187,
  233,
  162,
  152,
  239,
  188,
  140,
  228,
  184,
  141,
  232,
  166,
  129,
  232,
  167,
  163,
  233,
  135,
  138,
  227,
  128,
  129,
  228,
  184,
  141,
  232,
  166,
  129,
  230,
  160,
  135,
  231,
  130,
  185,
  227,
  128,
  129,
  228,
  184,
  141,
  232,
  166,
  129,
  232,
  175,
  173,
  230,
  176,
  148,
  232,
  175,
  141,
  227,
  128,
  129,
  228,
  184,
  141,
  232,
  166,
  129,
  229,
  164,
  154,
  228,
  189,
  153,
  230,
  150,
  135,
  230,
  156,
  172,
  239,
  188,
  140,
  229,
  166,
  130,
  230,
  158,
  156,
  230,
  178,
  161,
  230,
  156,
  137,
  228,
  184,
  187,
  233,
  162,
  152,
  239,
  188,
  140,
  232,
  175,
  183,
  231,
  155,
  180,
  230,
  142,
  165,
  232,
  191,
  148,
  229,
  155,
  158,
  226,
  128,
  156,
  233,
  151,
  178,
  232,
  129,
  138,
  226,
  128,
  157,
  34,
  125,
  93,
  44,
  34,
  109,
  111,
  100,
  101,
  108,
  34,
  58,
  34,
  103,
  112,
  116,
  45,
  51,
  46,
  53,
  45,
  116,
  117,
  114,
  98,
  111,
  34,
  44,
  34,
  116,
  101,
  109,
  112,
  101,
  114,
  97,
  116,
  117,
  114,
  101,
  34,
  58,
  49,
  44,
  34,
  112,
  114,
  101,
  115,
  101,
  110,
  99,
  101,
  95,
  112,
  101,
  110,
  97,
  108,
  116,
  121,
  34,
  58,
  48,
  125
],
  size: 1
}
],
  _next: undefined
}
},
  _queueTotalSize: 1,
  _started: true,
  _closeRequested: true,
  _pullAgain: false,
  _pulling: false,
  _strategySizeAlgorithm: [Function],
  _strategyHWM: 1,
  _pullAlgorithm: [Function],
  _cancelAlgorithm: [Function]
}
}  [TypeError: fetch failed] {
  cause:  [Error: connect ECONNREFUSED 127.0.0.1:8008] {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8008
}
}



这是全部日记

**Comment by Mr-zhao98** [comment]
好像是账号登录不行导致的

**Comment by xueandyue** [comment]
看这个 https://github.com/xueandyue/ChatGPT-3.5-AccessToken-Web/issues/21  。嗯嗯，那直接用备用部署(利用access_token)
