### ISSUE TITLE
连续提问会卡在哪里

### ISSUE THREAD

**Issue by Yanyutin753** [xueandyue/ChatGPT-3.5-AccessToken-Web#25]
![image](https://github.com/xueandyue/ChatGPT-3.5-AccessToken-Web/assets/132346501/95389ab9-65a2-4203-a886-f84e75ec5c9e)
不知道是什么问题，我用的是accessToken登录，我之前用faskGPT也会有这样的问题
该怎么解决呢

**Comment by Yanyutin753** [comment]
而且有的时候就是会不动，卡在那

**Comment by xueandyue** [comment]
用的什么浏览器，看看浏览器的console有没有报错，以及看看docker的日志有没有异常

**Comment by xueandyue** [comment]
你的应用只有你1个人用吗，如果很多人用，可能是性能问题。
