### ISSUE TITLE
账号版无法使用

### ISSUE THREAD

**Issue by edhnt455** [xueandyue/ChatGPT-3.5-AccessToken-Web#27]
![image](https://github.com/xueandyue/ChatGPT-3.5-AccessToken-Web/assets/59108157/1678880e-a7f6-4adf-abe3-99271c54309c)
提示这个，请问是什么原因呢

**Comment by xueandyue** [comment]
https://github.com/xueandyue/ChatGPT-3.5-AccessToken-Web/issues/21   可能是这个原因。你连docker 日志都不附上。。。
