### ISSUE TITLE
无法真正删除对话框

### ISSUE THREAD

**Issue by hhcwjss** [xueandyue/ChatGPT-3.5-AccessToken-Web#30]
大佬，你这个程序好像只能新建对话框，pandara也有记录，但是删除对话框的时候只能删该页面的，没有删除pandara那边，并且无法同步pandara使用的数据

**Comment by xueandyue** [comment]
本来就是这么设计的。所有数据保存在用户浏览器本地，也只是删除本地的数据，也不会同步官网的记录，更不会删除官网的记录。
