### ISSUE TITLE
有没有想法， 在第 13 天的时候自动更新 accesskey

### ISSUE THREAD

**Issue by imxintian** [xueandyue/ChatGPT-3.5-AccessToken-Web#6]

**Comment by xueandyue** [comment]
目前还在考虑，好像不好集成进来，还没决定

**Comment by xueandyue** [comment]
已解决Accesstoken需要手动更新的问题，可以看下README.md

**Comment by womenyiqijugeliziba** [comment]
我一直就在纠结这个事情，哈哈哈哈，没想到在你这看到了曙光，可以算前排围观不？

**Comment by xueandyue** [comment]
> 我一直就在纠结这个事情，哈哈哈哈，没想到在你这看到了曙光，可以算前排围观不？

哈哈

**Comment by womenyiqijugeliziba** [comment]
> 

大佬，我按照你的说明，操作顺序是这样的：
1、安装docker
2、安装python3.9
3、下载pandora
4、安装yarn
5、运行yarn install && yarn dev
但是，现在问题就来了：
1、到3这步，我不会用Linux新建token.txt文件，我可以用WinSCP登录，然后手动新建token.txt文件吗？如果可以，路径是什么，我找不到pandora文件夹。
2、到4这步，安装yarn后，（1）运行cd ChatGPT-3.5-AccessToken-Web命令后，再运行yarn install && yarn dev，提示ERROR: [Errno 2] No such file or directory: 'install
                     （2）直接运行yarn install && yarn dev也不行。请问应该怎么解决。
我是纯小白，Linux基础有限，还希望大佬不要嫌弃我，如果搭建好了，我愿意奉上我的屁股。

**Comment by xueandyue** [comment]
> > 
> 
> 大佬，我按照你的说明，操作顺序是这样的： 1、安装docker 2、安装python3.9 3、下载pandora 4、安装yarn 5、运行yarn install && yarn dev 但是，现在问题就来了： 1、到3这步，我不会用Linux新建token.txt文件，我可以用WinSCP登录，然后手动新建token.txt文件吗？如果可以，路径是什么，我找不到pandora文件夹。 2、到4这步，安装yarn后，（1）运行cd ChatGPT-3.5-AccessToken-Web命令后，再运行yarn install && yarn dev，提示ERROR: [Errno 2] No such file or directory: 'install （2）直接运行yarn install && yarn dev也不行。请问应该怎么解决。 我是纯小白，Linux基础有限，还希望大佬不要嫌弃我，如果搭建好了，我愿意奉上我的屁股。

哈哈，支持的话，奉上一个星星就行，有docker部署比较简单的，两行命令就行了。

确保有chatgpt官方账号
确保安装了docker，启动了docker
${username}是账号的值，${password}是账号的密码，${CODE}是设置密码，如果CODE=""则表示不设置密码
运行命令： docker pull xueandyue/next-web-pandora:latest
运行命令： docker run -e username="${username}" -e password="${password}" -e CODE="${CODE}" -p 3000:3000 -d xueandyue/next-web-pandora:latest
在浏览器访问[http://服务器域名(ip):3000/](http://xn--%28ip%29-pq8mn1jrviuyekr6d:3000/)

**Comment by womenyiqijugeliziba** [comment]
> > 大佬，我按照你的说明，操作顺序是这样的： 1、安装docker 2、安装python3.9 3、下载pandora 4、安装yarn 5、运行yarn install && yarn dev 但是，现在问题就来了： 1、到3这步，我不会用Linux新建token.txt文件，我可以用WinSCP登录，然后手动新建token.txt文件吗？如果可以，路径是什么，我找不到pandora文件夹。 2、到4这步，安装yarn后，（1）运行cd ChatGPT-3.5-AccessToken-Web命令后，再运行yarn install && yarn dev，提示ERROR: [Errno 2] No such file or directory: 'install （2）直接运行yarn install && yarn dev也不行。请问应该怎么解决。 我是纯小白，Linux基础有限，还希望大佬不要嫌弃我，如果搭建好了，我愿意奉上我的屁股。
> 
> 哈哈，支持的话，奉上一个星星就行，有docker部署比较简单的，两行命令就行了。
> 
> 确保有chatgpt官方账号 确保安装了docker，启动了docker ${username}是账号的值，${password}是账号的密码，${CODE}是设置密码，如果CODE=""则表示不设置密码 运行命令： docker pull xueandyue/next-web-pandora:latest 运行命令： docker run -e username="${username}" -e password="${password}" -e CODE="${CODE}" -p 3000:3000 -d xueandyue/next-web-pandora:latest 在浏览器访问[http://服务器域名(ip):3000/](http://xn--%28ip%29-pq8mn1jrviuyekr6d:3000/)

就在刚刚，我还没看到你的回复，我突然就顿悟了，完全在docker容器里运行就行的啊，是我自己没搞明白，另外，大佬，服务器上运行这个，有被墙的风险吗？我准备再注册十个账号，为你打星星

**Comment by xueandyue** [comment]
不好说。例如，有人举报你的网站，你的域名或者ip就有可能被墙。

**Comment by womenyiqijugeliziba** [comment]
> 

```json
{
  "cause": {
    "errno": -111,
    "code": "ECONNREFUSED",
    "syscall": "connect",
    "address": "127.0.0.1",
    "port": 8008
  }
}
```
大佬，安装好后，只要我输入文字，就会提示这个，请问这个是什么原因引起的呢

**Comment by xueandyue** [comment]
> > 
> 
> ```json
> {
>   "cause": {
>     "errno": -111,
>     "code": "ECONNREFUSED",
>     "syscall": "connect",
>     "address": "127.0.0.1",
>     "port": 8008
>   }
> }
> ```
> 
> 大佬，安装好后，只要我输入文字，就会提示这个，请问这个是什么原因引起的呢

可能服务还在初始化吧，等5分钟再用。或者重启docker容器，等5分钟，再试试

**Comment by womenyiqijugeliziba** [comment]
> ```json
> ```json
> {
>   "cause": {
>     "errno": -111,
>     "code": "ECONNREFUSED",
>     "syscall": "connect",
>     "address": "127.0.0.1",
>     "port": 8008
>   }
> }
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 大佬，安装好后，只要我输入文字，就会提示这个，请问这个是什么原因引起的呢
> 
> 可能服务还在初始化吧，等5分钟再用。或者重启docker容器，等5分钟，再试试
> ```

大佬，你没看错，时隔多年，我又来提问了：
假设我的
账号是abc@abc.com
密码是123
访问密码是789
那么我应该怎么写？
docker run -e username="abc@abc.com" -e password="123" -e CODE="789" -p 3000:3000 -d xueandyue/next-web-pandora:latest 

或者是
docker run -e username="${abc@abc.com}" -e password="${123}" -e CODE="${789}" -p 3000:3000 -d xueandyue/next-web-pandora:latest 

我在自己家服务器上安装的时候，忘记之前是怎么安装的了，哈哈哈哈哈哈，蜜汁尴尬。

**Comment by xueandyue** [comment]
docker run -e ***@***.***" -e password="123" -e CODE="789" -p 3000:3000 -d xueandyue/next-web-pandora:latest
&nbsp;


1073973789
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月16日(星期六) 凌晨0:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [xueandyue/ChatGPT-3.5-AccessToken-Web] 有没有想法， 在第 13 天的时候自动更新 accesskey (Issue #6)





  ```json {   "cause": {     "errno": -111,     "code": "ECONNREFUSED",     "syscall": "connect",     "address": "127.0.0.1",     "port": 8008   } }
 
大佬，安装好后，只要我输入文字，就会提示这个，请问这个是什么原因引起的呢
 
可能服务还在初始化吧，等5分钟再用。或者重启docker容器，等5分钟，再试试
   
大佬，你没看错，时隔多年，我又来提问了：
 假设我的
 ***@***.***
 密码是123
 访问密码是789
 那么我应该怎么写？
 docker run -e ***@***.***" -e password="123" -e CODE="789" -p 3000:3000 -d xueandyue/next-web-pandora:latest
 
或者是
 docker run -e ***@***.***}" -e password="${123}" -e CODE="${789}" -p 3000:3000 -d xueandyue/next-web-pandora:latest
 
我在自己家服务器上安装的时候，忘记之前是怎么安装的了，哈哈哈哈哈哈，蜜汁尴尬。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;
