### ISSUE TITLE
可以在前端加一个输入的accesstoken的输入框么？

### ISSUE THREAD

**Issue by biowr** [xueandyue/ChatGPT-3.5-AccessToken-Web#8]
这样就不用过期之后手动重启docker来配置token了，加油

**Comment by xueandyue** [comment]
感觉还不如加个功能：弄个定时任务，自动拿accesstoken,然后自动重启docker里面的服务

**Comment by xueandyue** [comment]
已解决Accesstoken需要手动更新的问题，可以看下README.md
